// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type NewTransaction struct {
	Isin   string `json:"isin"`
	Broker string `json:"broker"`
	// If the broker does not supply an ID for the transaction, an ID is generated based on
	// the rest of the data.
	BrokerID *string `json:"brokerId,omitempty"`
}

type Query struct {
}

type Security struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}
