// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Mutation struct {
}

type NewTransaction struct {
	Isin            string      `json:"isin"`
	Broker          string      `json:"broker"`
	Date            time.Time   `json:"date"`
	Exchange        string      `json:"exchange"`
	Amount          int         `json:"amount"`
	Price           *MoneyInput `json:"price"`
	TransactionCost *MoneyInput `json:"transactionCost,omitempty"`
	// If the broker does not supply an ID for the transaction, an ID is generated based on
	// the rest of the data.
	BrokerID *string `json:"brokerId,omitempty"`
}

type Query struct {
}

type Security struct {
	Isin         string `json:"isin"`
	Broker       string `json:"broker"`
	Exchange     string `json:"exchange"`
	Amount       int    `json:"amount"`
	AveragePrice *Money `json:"averagePrice"`
}
