package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"wealth-wizard/backend/graph/model"
	"wealth-wizard/backend/graph/resolvers"
)

// Securities is the resolver for the securities field.
func (r *queryResolver) Securities(ctx context.Context) ([]*model.Security, error) {
  return resolvers.Securities(ctx)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
